image: alpine:latest

stages:
  - build
  - test
  - deploy # dummy stage to follow the template guidelines
  - review
  - staging
  - canary
  - production
  - performance
  - cleanup

include:
  - template: Jobs/Build.gitlab-ci.yml
  - template: Jobs/Code-Quality.gitlab-ci.yml
  - template: Jobs/Deploy.gitlab-ci.yml
  - template: Security/Container-Scanning.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Management.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml


test:
  stage: test
  image: "python:3.7"
  script:
  - pip install -r requirements.txt
  - python setup.py test


deploy:
  stage: deploy
  variables:
    TWINE_USERNAME: $PRODUCTION_USERNAME
    TWINE_PASSWORD: $PRODUCTION_PASSWORD
  script:
    - pip install twine
    - python setup.py sdist
    - twine upload dist/*
  only:
    - tags