image: "python:3.7"

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - test
  - deploy

test:
  stage: test
  script:
  - python setup.py test


deploy_production:
  stage: deploy
  variables:
    TWINE_USERNAME: $PRODUCTION_USERNAME
    TWINE_PASSWORD: $PRODUCTION_PASSWORD
  script:
    - pip install twine
    - python setup.py sdist
    - twine upload dist/*
  only:
    - tags